LoseControlLocale = {}

if GetLocale() == "ruRU" then
	LoseControlLocale = {
		["Hibernate"] = "Спячка",
		["Starfire Stun"] = "Звездный огонь - оглушение",
		["Entangling Roots"] = "Гнев деревьев",
		["Bash"] = "Оглушить",
		["Pounce Bleed"] = "Кровоточащая рана",
		["Feral Charge Effect"] = "Звериная атака - эффект",
		-- Hunter
		["Intimidation"] = "Устрашение",
		["Scare Beast"] = "Отпугивание зверя",
		["Scatter Shot"] = "Дезориентирующий выстрел",
		["Improved Concussive Shot"] = "Улучшенный контузящий выстрел",
		["Concussive Shot"] = "Контузящий выстрел",
		["Freezing Trap Effect"] = "Эффект замораживающей ловушки",
		["Freezing Trap"] = "Замораживающая ловушка",
		["Frost Trap Aura"] = "Аура ледяной ловушки",
		["Frost Trap"] = "Ледяная ловушка",
		["Entrapment"] = "Удержание",
		["Wyvern Sting"] = "Укус виверны",
		["Counterattack"] = "Контратака",
		["Improved Wing Clip"] = "Безжалостно подрезать крылья",
		["Wing Clip"] = "Подрезать крылья",
		["Boar Charge"] = "Атака вепря",
		-- Mage
		["Polymorph"] = "Превращение",
		["Polymorph: Turtle"] = "Превращение: черепаха",
		["Polymorph: Pig"] = "Превращение в свинью",
		["Polymorph: Cow"] = "Превращение: корова",
		["Polymorph: Chicken"] = "Полиморф: цыпленок",
		["Counterspell - Silenced"] = "Антимагия - немота",
		["Impact"] = "Сотрясение",
		["Blast Wave"] = "Взрывная волна",
		["Frostbite"] = "Обморожение",
		["Frost Nova"] = "Кольцо льда",
		["Frostbolt"] = "Ледяная стрела",
		["Cone of Cold"] = "Конус холода",
		["Chilled"] = "Окоченение",
		-- Paladin
		["Hammer of Justice"] = "Молот правосудия",
		["Repentance"] = "Покаяние",
		-- Priest
		["Mind Control"] = "Контроль над разумом",
		["Psychic Scream"] = "Ментальный крик",
		["Blackout"] = "Затмение",
		["Silence"] = "Безмолвие",
		["Mind Flay"] = "Пытка разума",
		-- Rogue
		["Blind"] = "Ослепление",
		["Cheap Shot"] = "Подлый трюк",
		["Gouge"] = "Парализующий удар",
		["Kidney Shot"] = "Удар по почкам",
		["Sap"] = "Ошеломление",
		["Kick - Silenced"] = "Пинок - немота",
		["Crippling Poison"] = "Калечащий яд",
		-- Warlock
		["Death Coil"] = "Лик смерти",
		["Fear"] = "Страх",
		["Howl of Terror"] = "Вой ужаса",
		["Curse of Exhaustion"] = "Проклятие изнеможения",
		["Pyroclasm"] = "Огнесдвиг",
		["Aftermath"] = "Последствия",
		["Seduction"] = "Соблазн",
		["Spell Lock"] = "Запрет чар",
		["Inferno Effect"] = "Эффект инфернала",
		["Inferno"] = "Инфернал",
		["Cripple"] = "Увечье",
		-- Warrior
		["Charge Stun"] = "Атака-оглушение",
		["Intercept Stun"] = "Перехват оглушение.",
		["Intimidating Shout"] = "Устрашающий крик",
		["Revenge Stun"] = "Реванш - оглушение",
		["Concussion Blow"] = "Оглушающий удар",
		["Piercing Howl"] = "Пронзительный вой",
		["Shield Bash - Silenced"] = "Удар щитом - немота",
		--Shaman	
		["Frostbrand Weapon"] = "Оружие ледяного клейма",
		["Frost Shock"] = "Ледяной шок",
		["Earthbind"] = "Оковы земли",
		["Earthbind Totem"] = "Тотем оков земли",
		-- other
		["War Stomp"] = "Громовая поступь",
		["Tidal Charm"] = "Приливное подчинение",
		["Mace Stun Effect"] = "Эффект оглушения дробящего оружия",
		["Stun"] = "Оглушение",
		["Gnomish Mind Control Cap"] = "Гномская шапка контроля над разумом",
		["Reckless Charge"] = "Безрассудная атака",
		["Sleep"] = "Сон",
		["Dazed"] = "Замедление",
		["Freeze"] = "Холод",
		["Chill"] = "Стужа",
		["Charge"] = "Рывок",
	}
else
	LoseControlLocale = {
		["Hibernate"] = "Hibernate",
		["Starfire Stun"] = "Starfire Stun",
		["Entangling Roots"] = "Entangling Roots",
		["Bash"] = "Bash",
		["Pounce Bleed"] = "Pounce Bleed",
		["Feral Charge Effect"] = "Feral Charge Effect",
		-- Hunter
		["Intimidation"] = "Intimidation",
		["Scare Beast"] = "Scare Beast",
		["Scatter Shot"] = "Scatter Shot",
		["Improved Concussive Shot"] = "Improved Concussive Shot",
		["Concussive Shot"] = "Concussive Shot",
		["Freezing Trap Effect"] = "Freezing Trap Effect",
		["Freezing Trap"] = "Freezing Trap",
		["Frost Trap Aura"] = "Frost Trap Aura",
		["Frost Trap"] = "Frost Trap",
		["Entrapment"] = "Entrapment",
		["Wyvern Sting"] = "Wyvern Sting",
		["Counterattack"] = "Counterattack",
		["Improved Wing Clip"] = "Improved Wing Clip",
		["Wing Clip"] = "Wing Clip",
		["Boar Charge"] = "Boar Charge",
		-- Mage
		["Polymorph"] = "Polymorph",
		["Polymorph: Turtle"] = "Polymorph: Turtle",
		["Polymorph: Pig"] = "Polymorph: Pig",
		["Polymorph: Cow"] = "Polymorph: Cow",
		["Polymorph: Chicken"] = "Polymorph: Chicken",
		["Counterspell - Silenced"] = "Counterspell - Silenced",
		["Impact"] = "Impact",
		["Blast Wave"] = "Blast Wave",
		["Frostbite"] = "Frostbite",
		["Frost Nova"] = "Frost Nova",
		["Frostbolt"] = "Frostbolt",
		["Cone of Cold"] = "Cone of Cold",
		["Chilled"] = "Chilled",
		-- Paladin
		["Hammer of Justice"] = "Hammer of Justice",
		["Repentance"] = "Repentance",
		-- Priest
		["Mind Control"] = "Mind Control",
		["Psychic Scream"] = "Psychic Scream",
		["Blackout"] = "Blackout",
		["Silence"] = "Silence",
		["Mind Flay"] = "Mind Flay",
		-- Rogue
		["Blind"] = "Blind",
		["Cheap Shot"] = "Cheap Shot",
		["Gouge"] = "Gouge",
		["Kidney Shot"] = "Kidney Shot",
		["Sap"] = "Sap",
		["Kick - Silenced"] = "Kick - Silenced",
		["Crippling Poison"] = "Crippling Poison",
		-- Warlock
		["Death Coil"] = "Death Coil",
		["Fear"] = "Fear",
		["Howl of Terror"] = "Howl of Terror",
		["Curse of Exhaustion"] = "Curse of Exhaustion",
		["Pyroclasm"] = "Pyroclasm",
		["Aftermath"] = "Aftermath",
		["Seduction"] = "Seduction",
		["Spell Lock"] = "Spell Lock",
		["Inferno Effect"] = "Inferno Effect",
		["Inferno"] = "Inferno",
		["Cripple"] = "Cripple",
		-- Warrior
		["Charge Stun"] = "Charge Stun",
		["Intercept Stun"] = "Intercept Stun",
		["Intimidating Shout"] = "Intimidating Shout",
		["Revenge Stun"] = "Revenge Stun",
		["Concussion Blow"] = "Concussion Blow",
		["Piercing Howl"] = "Piercing Howl",
		["Shield Bash - Silenced"] = "Shield Bash - Silenced",
		--Shaman	
		["Frostbrand Weapon"] = "Frostbrand Weapon",
		["Frost Shock"] = "Frost Shock",
		["Earthbind"] = "Earthbind",
		["Earthbind Totem"] = "Earthbind Totem",
		-- other
		["War Stomp"] = "War Stomp",
		["Tidal Charm"] = "Tidal Charm",
		["Mace Stun Effect"] = "Mace Stun Effect",
		["Stun"] = "Stun",
		["Gnomish Mind Control Cap"] = "Gnomish Mind Control Cap",
		["Reckless Charge"] = "Reckless Charge",
		["Sleep"] = "Sleep",
		["Dazed"] = "Dazed",
		["Freeze"] = "Freeze",
		["Chill"] = "Chill",
		["Charge"] = "Charge",
	}
end